# Exercise of Numpy Array

Question 1: Create a 4X2 integer array and Prints its attributes
a. The shape of an array.
b. Array dimensions.

In [9]:
import numpy as np

a_list = [[10, 5],[10, 4],[10, 3],[10, 2]]
a_np = np.array(a_list)

print(a_np.shape)
print(a_np.ndim)
print(a_np)

(4, 2)
2
[[10  5]
 [10  4]
 [10  3]
 [10  2]]


Question 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [10]:
a_np = np.arange(100, 200, 10)
a_np = a_np.reshape(5, 2)

print(a_np)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


Question 3: Following is the provided numPy array. return array of items in the third column from all rows

In [12]:
import numpy
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

print(sampleArray)
print(sampleArray[:, 2])

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[33 66 99]


Question 4: Following is the given numpy array return array of odd rows and even columns

In [17]:
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)
print("\n", sampleArray[::2, 1::2])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 [[ 6 12]
 [30 36]
 [54 60]]


Question 5: Add the following two NumPy arrays and Modify a result array by calculating the square root of each element

In [18]:
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

array_res = arrayOne + arrayTwo
print(array_res)
print(np.sqrt(array_res))

[[20 39 33]
 [25 25 28]]
[[4.47213595 6.244998   5.74456265]
 [5.         5.         5.29150262]]
